version: '3.9'

services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
  web_app:
    build:
      dockerfile: Dockerfile
      context: .
    image: darqube-api
    depends_on:
      - db
    ports:
      - "5000:5000"